from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from core.version_compare import compare_versions
from core.quote_engine import generate_quote
from pathlib import Path

def export_quote_pdf(part_id: str, output_path: str = None):
    export_dir = Path("data/exports")
    export_dir.mkdir(parents=True, exist_ok=True)
    pdf_path = export_dir / f"{part_id}_quote.pdf"
    c = canvas.Canvas(str(output_path or pdf_path), pagesize=A4)
    width, height = A4
    y = height - 50

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, f"📄 Axis5 Quote & Version Report for Part: {part_id}")
    y -= 40

    quote = generate_quote(part_id)
    c.setFont("Helvetica", 11)
    c.drawString(50, y, f"Process: {quote.get('process','-')} | Material: {quote.get('material','-')} | Qty: {quote.get('quantity','-')}")
    y -= 20
    c.drawString(50, y, f"Cost/Part: ₹{quote.get('unit_cost','-')} | Setup Cost: ₹{quote.get('setup_cost','-')} | Lead Time: {quote.get('lead_time_days','-')}d")
    y -= 30

    comp = compare_versions(part_id)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "🔍 V1 vs V2 Comparison")
    y -= 20
    c.setFont("Helvetica", 10)
    if 'error' not in comp:
        c.drawString(50, y, f"DFM Score: {comp['dfm_score_v1']} → {comp['dfm_score_v2']}")
        y -= 15
        c.drawString(50, y, f"Cost/part: ₹{comp['cost_per_part_v1']} → ₹{comp['cost_per_part_v2']}")
        y -= 15
        c.drawString(50, y, f"Material: {comp['material_v1']} → {comp['material_v2']}")
        y -= 15
        c.drawString(50, y, f"Process: {comp['process_v1']} → {comp['process_v2']}")
        y -= 15
        c.drawString(50, y, f"Fixes in V2: {', '.join(comp['fixes_applied']) if comp['fixes_applied'] else 'None'}")
        y -= 20
    else:
        c.drawString(50, y, "Version comparison not available.")
        y -= 20

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, y, f"Vendor: {quote.get('vendor_recommendation',{}).get('name','N/A')}")
    y -= 15
    c.drawString(50, y, f"Generated by Axis5 at your request.")

    c.save()
    return f"/data/exports/{part_id}_quote.pdf"
